name: 'Build SAM GitHub Actions'
branding:
  icon: 'terminal'
  color: 'orange'
inputs:
  params:
    description: 'AWS SAM build params'
    required: false
  workspace:
    description: 'Relative path under $GITHUB_WORKSPACE to place the project'
    required: false
    default: .
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Setup AWS CLI
      run: pip install awscli
      shell: bash

    - name: Setup AWS SAM CLI
      run: pip install aws-sam-cli
      shell: bash

    - name: Build AWS SAM
      run: |
        cd ${{ inputs.workspace }}
        sam build -b dist ${{ inputs.params }} && \
        if [ -e samconfig.toml ];then cp samconfig.toml dist/samconfig.toml; fi
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ inputs.workspace }}/dist
