name: 'Build SAM GitHub Actions'
branding:
  icon: 'terminal'
  color: 'orange'
inputs:
  params:
    description: 'AWS SAM build params'
    required: false
  workspace:
    description: 'Relative path under $GITHUB_WORKSPACE to place the project'
    required: false
runs:
  using: 'docker'
  image: './Dockerfile'
