name: 'Build SAM GitHub Actions'
branding:
  icon: 'terminal'
  color: 'orange'
inputs:
  params:
    description: 'AWS SAM build params'
    required: false
  workspace:
    description: 'Relative path under $GITHUB_WORKSPACE to place the project'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - uses: actions/setup-node@v3
    - uses: actions/setup-python@v4
    - run: pip install awscli
    - run: pip install aws-sam-cli
    - run: build-sam.sh
    - uses: SonarSource/sonarcloud-github-action@master
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
